{
 "title": "redis",
 "description": "redis",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "数据源", "query": "prometheus" },
   { "name": "job", "label": "redis 集群", "query": { "query": "label_values(redis_up, job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "role",
    "label": "role",
    "query": {
     "query": "label_values(redis_instance_info{job=\"$job\",instance=\"$instance\"},role)"
    }
   },
   { "name": "interval", "label": "interval", "query": "20s,30s,40s,1m" }
  ]
 },
 "panels": [
  {
   "title": "大盘操作速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(redis_commands_processed_total[1m])) by(job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "大盘总操作耗时",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance, job) (delta(redis_commands_duration_seconds_total[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "同类型操作耗时超过1s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "delta(redis_commands_duration_seconds_total[1m] ) >1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "大盘连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "主进程cpu使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(rate(redis_cpu_user_seconds_total[1m]) + rate(redis_cpu_sys_seconds_total[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "redis_memory_used_rss_bytes", "legendFormat": "rss--{{job}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 18 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{job=~\"$job\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 18 },
   "targets": [
    {
     "expr": "redis_connected_clients{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "碎片率",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{job=~\"$job\"}[$interval])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{job=~\"$job\"}[$interval])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "同步滞后时间",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "delta(redis_commands_duration_seconds_total{job=\"$job\", instance=\"$instance\"}[1m]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "master vs slave",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_instance_info{job=~\"$job\",instance=~\"$instance\",role=\"master\"} or (redis_instance_info{job=~\"$job\",instance=~\"$instance\",role=\"slave\"})-1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "主进程cpu使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "(rate(redis_cpu_user_seconds_total{job=~\"$job\"}[1m]) + rate(redis_cpu_sys_seconds_total{job=~\"$job\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=~\"$job\"} ",
     "legendFormat": "used---{{job}}--{{instance}}"
    },
    {
     "expr": "redis_memory_used_rss_bytes{job=~\"$job\"}",
     "legendFormat": "rss--{{job}}--{{instance}}"
    }
   ]
  },
  {
   "title": "Redis connected clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_connected_clients{job=~\"$job\"}",
     "legendFormat": "redis_connected_clients---{{job}}"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20,rate(redis_commands_total{job=~\"$job\"} [$interval]))",
     "legendFormat": "{{ cmd }}---{{job}}---{{instance}}"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands_processed_total{job=~\"$job\"}[$interval])"
    }
   ]
  },
  {
   "title": "操作耗时top",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "expr": "delta(redis_commands_duration_seconds_total{job=~\"$job\"}[1m])",
     "legendFormat": "{{cmd}}---{{job}}--{{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{job=~\"$job\"}[5m])",
     "legendFormat": "input---{{job}}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{job=~\"$job\"}[5m])",
     "legendFormat": "output---{{job}}"
    }
   ]
  },
  {
   "title": "操作平均耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "delta(redis_commands_duration_seconds_total{job=~\"$job\"}[$interval])/delta(redis_commands_total{job=~\"$job\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总操作耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "targets": [
    {
     "expr": "sum(delta(redis_commands_duration_seconds_total{job=~\"$job\"}[1m])) by (instance,job)"
    }
   ]
  },
  {
   "title": "node_epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 52 },
   "targets": [
    {
     "expr": "redis_cluster_my_epoch{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "客户端最大输出buffer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
   "repeat": "interval",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_client_recent_max_output_buffer_bytes{job=~\"$job\"}",
     "legendFormat": "redis_client_recent_max_output_buffer_bytes---{{job}}"
    }
   ]
  },
  {
   "title": "fork耗时",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_latest_fork_seconds{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "key和过期key总数量",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "redis_db_keys{job=~\"$job\"}",
     "legendFormat": "{{__name__}}--{{job}}"
    },
    {
     "expr": "redis_db_keys_expiring{job=~\"$job\"}",
     "legendFormat": "{{__name__}}--{{job}}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$job\"}) by (db,job)",
     "legendFormat": "{{ job }} "
    }
   ]
  },
  {
   "title": "总操作耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "targets": [
    {
     "expr": "sum(delta(redis_commands_duration_seconds_total{job=~\"$job.*\"}[$interval])) by (instance,job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cluster_epoch",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 72 },
   "targets": [
    {
     "expr": "redis_cluster_current_epoch{job=~\"$job\"} ",
     "legendFormat": "{{__name__}}---{{instance}}"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{job=~\"$job\"}) - sum (redis_db_keys_expiring{job=~\"$job\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{job=~\"$job\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{job=~\"$job\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "activedefrag",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "redis_defrag_hits{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_defrag_misses{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_defrag_key_hits{job=~\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "redis_defrag_key_misses{job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}