{
 "title": "vm监控",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "alertmanager当前告警数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "alertmanager_alerts" }
   ]
  },
  {
   "title": "alertmanager接受告警数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "increase(alertmanager_alerts_received_total[1m])"
    }
   ]
  },
  {
   "title": "alertmanger告警推送次数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "delta(alertmanager_notification_requests_total[1m])"
    }
   ]
  },
  {
   "title": "alertmanager集群重连失败次数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "increase(alertmanager_cluster_reconnections_failed_total[1m])"
    }
   ]
  },
  {
   "title": "prometheus抓取速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[1m])"
    }
   ]
  },
  {
   "title": "vmalert上次评估拉取数据",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "vmalert_alerting_rules_last_evaluation_series_fetched"
    }
   ]
  },
  {
   "title": "vmalert规则评估耗时",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "delta(vmalert_iteration_duration_seconds_sum[30s])"
    }
   ]
  },
  {
   "title": "http请求次数速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(vm_http_requests_all_total[1m]) "
    }
   ]
  },
  {
   "title": "vm insert 行写入速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(vm_rows_inserted_total[1m])"
    }
   ]
  },
  {
   "title": "vmstorage写入存储速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(vm_rows_added_to_storage_total[1m])"
    }
   ]
  },
  {
   "title": "vmagent写入行数速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(vmagent_rows_inserted_total[1m])"
    }
   ]
  },
  {
   "title": "vminsert  select拨号写入速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(vm_tcpdialer_written_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "vmselect在storage中1分钟请求次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "delta(vm_vmselect_rpc_requests_total[1m])"
    }
   ]
  },
  {
   "title": "reload失败数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "delta(vmagent_relabel_config_reloads_errors_total[1m]) "
    }
   ]
  },
  {
   "title": "vminsert 写超时数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "vm_tcpdialer_write_timeouts_total"
    }
   ]
  },
  {
   "title": "抓取目标状态up/down",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "vm_promscrape_targets" }
   ]
  },
  {
   "title": "vminsert请求耗时分布",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "vminsert_request_duration_seconds_bucket"
    }
   ]
  },
  {
   "title": "写入速率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(vm_tcplistener_written_bytes_total[1m])"
    }
   ]
  },
  {
   "title": "抓取次数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "delta(vm_promscrape_scrapes_total[1m])",
     "legendFormat": "scrapes"
    },
    {
     "expr": "delta(vm_promscrape_scrapes_timed_out_total[1m])",
     "legendFormat": "timeout--scrapes"
    },
    {
     "expr": "delta(vm_promscrape_scrapes_failed_total[1m])",
     "legendFormat": "failed--scrapes"
    }
   ]
  },
  {
   "title": "up",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "up" }
   ]
  },
  { "title": "vmagent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "服务发现总耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "vm_promscrape_service_discovery_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "vmagent连接数",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "targets": [
    { "expr": "vm_promscrape_conns" }
   ]
  }
 ]
}