{
 "title": "kafka",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(kafka_brokers, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{job=\"$job\"},topic)"
    }
   },
   {
    "name": "consumergroup",
    "query": {
     "query": "label_values(kafka_consumergroup_current_offset{job=\"$job\",topic=\"$topic\"},consumergroup)"
    }
   },
   {
    "name": "broker",
    "label": "broker",
    "query": {
     "query": "label_values(kafka_broker_info{job=\"$job\"},address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "集群节点信息",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_broker_info{job=\"$job\"}"
    }
   ]
  },
  {
   "title": "集群总速率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job) (rate(kafka_topic_partition_current_offset{job=\"$job\"}[1m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "集群大盘速率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[1m])) by(job)"
    }
   ]
  },
  {
   "title": "Production (5 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_topic_partition_current_offset{job=\"$job\", topic=\"$topic\"}[30s]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (kafka_consumergroup_lag{instance=\"$instance\", consumergroup=~\"$consumergroup\"})",
     "legendFormat": "{{consumergroup}} ({{topic}})"
    }
   ]
  },
  {
   "title": "同步副本",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "kafka_topic_partition_in_sync_replica{job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Consume (5 minutes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\",consumergroup=~\"$consumergroup\"}[1m])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} ({{topic}})"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic!=\"__consumer_offsets\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "消费堆积",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(consumergroup, topic) (kafka_consumergroup_lag{instance=~\"$instance\"})"
    }
   ]
  }
 ]
}