{
 "title": "zookeeper",
 "description": "Dashboard for https://github.com/dabealu/zookeeper-exporter\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(zk_up,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(zk_up{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "version",
    "query": {
     "query": "label_values(zk_version{job=~\"$job\", instance=~\"$instance\"}, version)"
    }
   },
   {
    "name": "zk_host",
    "query": {
     "query": "label_values(zk_packets_received{job=~\"$job\", instance=~\"$instance\"}, zk_host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "leader情况",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "zk_server_leader{job=\"$job\"}",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "zk_watch_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_up{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zk_server_leader{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Pakages Recieved",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zk_packets_received{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ zk_host}}"
    }
   ]
  },
  {
   "title": "ZK Version",
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "options": { "content": "$version\n\n\n" },
   "targets": [
    {}
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{zk_host}}"
    },
    {
     "expr": "zk_max_file_descriptor_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Ephemerals Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "zk_ephemerals_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Min Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "zk_min_latency{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host}}"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "expr": "zk_max_latency{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host}}"
    }
   ]
  },
  {
   "title": "Pakages Sent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zk_packets_sent{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Approx Data Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "zk_approximate_data_size{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host}}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_num_alive_connections{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host}}"
    }
   ]
  },
  {
   "title": "Znode Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "zk_znode_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_avg_latency{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zk_outstanding_requests{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ zk_host}}"
    }
   ]
  }
 ]
}